---
- name: Install zsh
  hosts: "{{ target_hosts }}"
  become: yes
  vars:
    nvim_folder: /opt/zsh
  tasks:
    - name: Install
      apt:
        update_cache: yes
        cache_valid_time: 86400 
        name:
          - curl 
          - gcc 
          - make 
          - default-libmysqlclient-dev 
          - libssl-dev 
          - zlib1g-dev 
          - libbz2-dev 
          - libreadline-dev 
          - libsqlite3-dev 
          - llvm 
          - libncurses5-dev 
          - libncursesw5-dev 
          - xz-utils 
          - tk-dev 
          - libffi-dev 
          - liblzma-dev 
          - python3-openssl 
          - git 
          - zsh
        state: present

    - name: Set zsh as default shell
      shell: chsh -s /bin/zsh

    - name: Setup theme and plugins
      shell: |
        sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"

        git clone https://github.com/spaceship-prompt/spaceship-prompt.git "$ZSH_CUSTOM/themes/spaceship-prompt" --depth=1
        ln -s "$ZSH_CUSTOM/themes/spaceship-prompt/spaceship.zsh-theme" "$ZSH_CUSTOM/themes/spaceship.zsh-theme"

        git clone https://github.com/zsh-users/zsh-autosuggestions ${ZSH_CUSTOM:-~/.oh-my-zsh/custom}/plugins/zsh-autosuggestions
        git clone https://github.com/zsh-users/zsh-syntax-highlighting.git ${ZSH_CUSTOM:-~/.oh-my-zsh/custom}/plugins/zsh-syntax-highlighting

        mkdir -p ~/.fonts
        git clone https://github.com/pdf/ubuntu-mono-powerline-ttf.git ~/.fonts/ubuntu-mono-powerline-ttf
        fc-cache -vf

        rm -rf ~/.zshrc
        ln -s $(pwd)/.zshrc ~/.zshrc
